<?php
/**
 * Module 2 — Authentication: Reset Password (step 2 of 2)
 * Reached via the link generated by forgot-password.php. Validates the
 * token + expiry, then lets the user set a new password.
 */
require_once __DIR__ . '/config/app_config.php';
require_once __DIR__ . '/config/db_connect.php';
require_once __DIR__ . '/includes/functions.php';

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$errors = [];
$token = trim($_GET['token'] ?? $_POST['token'] ?? '');
$tokenValid = false;
$userId = null;

if ($token !== '') {
    $stmt = $pdo->prepare(
        "SELECT id, reset_token_expiry FROM users WHERE reset_token = ?"
    );
    $stmt->execute([$token]);
    $user = $stmt->fetch();

    if ($user && $user['reset_token_expiry'] && strtotime($user['reset_token_expiry']) > time()) {
        $tokenValid = true;
        $userId = (int) $user['id'];
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && $tokenValid) {

    if (!verify_csrf($_POST['csrf_token'] ?? null)) {
        $errors[] = 'Your session expired. Please try again.';
    }

    $password = $_POST['password'] ?? '';
    $confirmPassword = $_POST['confirm_password'] ?? '';

    if (!is_strong_password($password)) {
        $errors[] = 'Password must be at least 8 characters and include a letter and a number.';
    }
    if ($password !== $confirmPassword) {
        $errors[] = 'Passwords do not match.';
    }

    if (empty($errors)) {
        $passwordHash = password_hash($password, PASSWORD_DEFAULT);

        $update = $pdo->prepare(
            "UPDATE users SET password_hash = ?, reset_token = NULL, reset_token_expiry = NULL WHERE id = ?"
        );
        $update->execute([$passwordHash, $userId]);

        set_flash('success', 'Your password has been reset. You can now log in.');
        redirect('/login.php');
    }
}

$pageTitle = "Reset Password";
require_once __DIR__ . '/includes/header.php';
require_once __DIR__ . '/includes/flash.php';
?>

<section class="auth-section">
  <div class="auth-card glass" data-reveal>
    <span class="section-eyebrow">Account Recovery</span>

    <?php if (!$tokenValid): ?>
      <h1>Link expired or invalid</h1>
      <p class="auth-sub">
        This password reset link is no longer valid. Reset links expire after 1 hour,
        or may have already been used.
      </p>
      <div class="auth-links">
        <a href="<?= BASE_URL ?>/forgot-password.php">Request a new reset link</a>
      </div>
    <?php else: ?>
      <h1>Set a new password</h1>
      <p class="auth-sub">Choose a new password for your account.</p>

      <?php if (!empty($errors)): ?>
        <div class="form-error" style="margin-bottom:1rem;">
          <?php foreach ($errors as $err): ?>
            <div><i class="bi bi-exclamation-circle"></i> <?= e($err) ?></div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>

      <form method="post" action="<?= BASE_URL ?>/reset-password.php" novalidate>
        <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
        <input type="hidden" name="token" value="<?= e($token) ?>">

        <label for="password">New password</label>
        <input type="password" class="form-control" id="password" name="password"
               placeholder="At least 8 characters, 1 letter, 1 number" minlength="8" required>

        <label for="confirm_password">Confirm new password</label>
        <input type="password" class="form-control" id="confirm_password" name="confirm_password"
               placeholder="Re-enter your new password" minlength="8" required>

        <button type="submit" class="btn-gradient">Reset Password</button>
      </form>
    <?php endif; ?>
  </div>
</section>

<?php require_once __DIR__ . '/includes/footer.php'; ?>
